### ISSUE TITLE
pagination problem

### ISSUE THREAD

**Issue by cpfarher** [ratiw/vuetable-2-tutorial-bootstrap#1]
```
<vuetable ref="vuetable"
    api-url="http://vuetable.ratiw.net/api/users"
    :fields="['name', 'email', 'birthdate']"
  ></vuetable>
```
shows warning and not render table:

`vuetable: pagination-path "links.pagination" not found. It looks like the data returned from the sever does not have pagination information or you may have set it incorrectly.`

**Comment by ratiw** [comment]
@cpfarher Have you followed the [tutorial](https://github.com/ratiw/vuetable-2-tutorial/blob/master/doc/README.md)? What lesson that you encountered the error?

**Comment by cpfarher** [comment]
I am so sorry, I forget to import the pagination component... :|
